### ISSUE TITLE
Android 6.0 

### ISSUE THREAD

**Issue by pharidali** [mayubao/KuaiChuan#2]
Please Made support to android 6.0

**Comment by mayubao** [comment]
I have solved most problem about permission model in android 6.0, but I have no android real device which high than android 6.0. If you have android 6.0 device and run it error , please show me the log. Thx

**Comment by mayubao** [comment]
@pharidali The problem you say has been solved!

**Comment by pharidali** [comment]
Hello Please Update Demo App link. :)

Thanks in Advance. 😊

**Comment by mayubao** [comment]
I have updated the Demo App link...
Thanks for your advice!

**Comment by pharidali** [comment]
Other Device Working Fine But In Android 6.0 When File is Selected And Click On Send Then Force Stop. . pleaSe Fix This.

**Comment by mayubao** [comment]
I have fixed this problem In Android 6.0.

**Comment by mayubao** [comment]
The Bugly SDK has been integrated in this app. If this app has some exception occurred in the runtime, I will receive some reports about the exception.
